title: "Andrea Pop-Catalisan"
author: "Andrea Pop-Catalisan"
description: "Paris School of Economics"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "/CV_APC.pdf", title: "CV"}
  - {file: "index.html", title: "Research"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:andrea.pop@psemail.eu"}
  - {title: PSE, icon: rss, url: "https://www.parisschoolofeconomics.eu/equipes/andrea-pop-catalisan/"}
  - {title: Linkedin, icon: linkedin, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
